// player/svelte/default-theme/src/components/sliders/VolumeSlider.svelte
<media-volume-slider class="vds-slider">
  <div class="vds-slider-track" />
  <div class="vds-slider-track-fill vds-slider-track" />
  <media-slider-preview class="vds-slider-preview" noClamp>
    <media-slider-value class="vds-slider-value" />
  </media-slider-preview>
  <div class="vds-slider-thumb" />
</media-volume-slider>

// player/vue/default-theme/src/components/sliders/VolumeSlider.vue
<template>
  <media-volume-slider class="vds-slider">
    <div class="vds-slider-track" />
    <div class="vds-slider-track-fill vds-slider-track" />
    <media-slider-preview class="vds-slider-preview" no-clamp>
      <media-slider-value class="vds-slider-value" />
    </media-slider-preview>
    <div class="vds-slider-thumb" />
  </media-volume-slider>
</template>
